name: Build Windows Executable

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Install Qt5
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        arch: 'win64_msvc2019_64'
        tools: 'tools_cmake'
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DQt5_DIR="${{ env.Qt5_Dir }}"
        
    - name: Build
      run: |
        cd build
        cmake --build . --config Release --parallel
        
    - name: Deploy Qt dependencies
      run: |
        mkdir dist
        copy build\\Release\\MedianXLOfflineTools.exe dist\\
        cd dist
        windeployqt.exe MedianXLOfflineTools.exe --release --no-translations --no-system-d3d-compiler --no-opengl-sw
        
    - name: Create portable package
      run: |
        cd dist
        echo "MedianXL Offline Tools - Portable Version" > README.txt
        echo "" >> README.txt
        echo "Version: ${{ github.sha }}" >> README.txt
        echo "Built: $(Get-Date)" >> README.txt
        echo "Platform: Windows x64" >> README.txt
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: MedianXLOfflineTools-Windows-x64
        path: dist/
        retention-days: 90
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/MedianXLOfflineTools.exe
        name: MedianXL Offline Tools ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y qt5-qmake qtbase5-dev qttools5-dev cmake build-essential
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cd build
        make -j$(nproc)
        
    - name: Create Linux package
      run: |
        mkdir dist-linux
        cp build/MedianXLOfflineTools dist-linux/
        cp README.md dist-linux/
        echo "MedianXL Offline Tools - Linux Version" > dist-linux/README.txt
        echo "Run with: ./MedianXLOfflineTools" >> dist-linux/README.txt
        
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: MedianXLOfflineTools-Linux-x64
        path: dist-linux/
        retention-days: 90